name: Build

on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1


      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Nuget Restore TrustJack
        run: nuget restore $Env:GITHUB_WORKSPACE\TrustJack\TrustJacker.sln
      
      - name: Nuget Install Costura.Fody
        run: nuget install Costura.Fody -Version 3.3.3 -OutputDirectory D:\a\RedCsharp\RedCsharp\TrustJack\packages

      - name: Build TrustJack
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\TrustJack\TrustJacker.csproj /property:Configuration=Release

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\SharpHound3\SharpHound3.sln
          
      - name: Build SharpHound3
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpHound3\SharpHound3\SharpHound3.csproj /property:Configuration=Release
          
      - name: Build SafetyKatz
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SafetyKatz\SafetyKatz\SafetyKatz.csproj /property:Configuration=Release
          
      - name: Build Grouper2
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\Grouper2\Grouper2\Grouper2.csproj /property:Configuration=Release
          
      - name: Build Rubeus
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\Rubeus\Rubeus\Rubeus.csproj /property:Configuration=Release
          
      - name: Build SharpDomainSpray
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpDomainSpray\SharpDomainSpray.csproj /property:Configuration=Release
          
      - name: Nuget Restore SharPersist
        run: nuget restore $Env:GITHUB_WORKSPACE\SharPersist\SharPersist.sln
      
      - name: Nuget Install Costura.Fody
        run: nuget install Costura.Fody -Version 3.3.3 -OutputDirectory D:\a\RedCsharp\RedCsharp\SharPersist\packages
      
      - name: Nuget Install TaskScheduler
        run: nuget install TaskScheduler -Version 2.8.11 -OutputDirectory D:\a\RedCsharp\RedCsharp\SharPersist\packages
          
      - name: Build SharPersist
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharPersist\SharPersist\SharPersist.csproj /property:Configuration=Release
          
      - name: Nuget Restore SharpLocker
        run: nuget restore $Env:GITHUB_WORKSPACE\SharpLocker\SharpLocker.sln
          
      - name: Build SharpLocker
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpLocker\SharpLocker\SharpLocker.csproj /property:Configuration=Release
          
      - name: Nuget Restore PurpleSharp
        run: nuget restore $Env:GITHUB_WORKSPACE\PurpleSharp\PurpleSharp.sln
          
      - name: Build PurpleSharp
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\PurpleSharp\PurpleSharp\PurpleSharp.csproj /property:Configuration=Release

      - name: Build SharpBlock
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpBlock\SharpBlock.csproj /property:Configuration=Release

      - name: Build SharpDump
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpDump\SharpDump\SharpDump.csproj /property:Configuration=Release

      - name: Build Seatbelt
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\Seatbelt\Seatbelt\Seatbelt.csproj /property:Configuration=Release
      
      - name: Build SharpShares
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SharpShares\SharpShares.csproj /property:Configuration=Release
     
      - name: Setup csc.exe
        uses: yoavain/Setup-CSC@v5

      - name: CSC SpaceRunner
        working-directory: SpaceRunner
        run: csc.exe /unsafe /platform:x64 /preferreduilang:en-US /filealign:512 /out:spacerunner.exe /target:exe spacerunner.cs

      - uses: actions/upload-artifact@master
        with:
          name: SharpHound3
          path: SharpHound3\SharpHound3\bin\Release\SharpHound.exe
      - uses: actions/upload-artifact@master
        with:
          name: SafetyKatz
          path: SafetyKatz\SafetyKatz\bin\Release\SafetyKatz.exe
      - uses: actions/upload-artifact@master
        with:
          name: Grouper2
          path: Grouper2\Grouper2\bin\Release\Grouper2.exe
      - uses: actions/upload-artifact@master
        with:
          name: Rubeus
          path: Rubeus\Rubeus\bin\Release\Rubeus.exe
      - uses: actions/upload-artifact@master
        with:
          name: SharpDomainSpray
          path: SharpDomainSpray\bin\Release\SharpDomainSpray.exe
      - uses: actions/upload-artifact@master
        with:
          name: SharPersist
          path: SharPersist\SharPersist\bin\Release\SharPersist.exe
      - uses: actions/upload-artifact@master
        with:
          name: SharpLocker
          path: SharpLocker\SharpLocker\bin\Release\SharpLocker.exe
          
      - uses: actions/upload-artifact@master
        with:
          name: PurpleSharp
          path: PurpleSharp\PurpleSharp\bin\Release\Simulator.exe

      - uses: actions/upload-artifact@master
        with:
          name: SharpBlock
          path: SharpBlock\bin\Release\SharpBlock.exe

      - uses: actions/upload-artifact@master
        with:
          name: TrustJack
          path: TrustJack\bin\Release\POPTHATSHELLBOI.exe

      - uses: actions/upload-artifact@master
        with:
          name: SharpDump
          path: SharpDump\SharpDump\bin\Release\SharpDump.exe

      - uses: actions/upload-artifact@master
        with:
          name: Seatbelt
          path: Seatbelt\Seatbelt\bin\Release\Seatbelt.exe
      
      - uses: actions/upload-artifact@master
        with:
          name: SharpShares
          path: SharpShares\bin\Release\SharpShares.exe
      
      - uses: actions/upload-artifact@master
        with:
          name: SpaceRunner
          path: SpaceRunner\spacerunner.exe
